analyzer_rules:
  - unused_import

included:
  - Sources
  - Tests

opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty 
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - lower_acl_than_parent
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - reduce_into
  - sorted_first_last
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

force_unwrapping: error

disabled_rules:
  - identifier_name
  - type_name
  - multiline_function_chains
  - multiple_closures_with_trailing_closure
  - todo

line_length:
  warning: 150
  ignores_comments: true

file_length: 750
large_tuple: 3
function_parameter_count: 10