language: swift
osx_image: xcode11.1
env:
  global:
  - PACKAGE_SCHEME="ZamzamKit-Package"
  matrix:
    - DESTINATION="arch=x86_64" SCHEME="$PACKAGE_SCHEME" RUN_TESTS="YES"
    - DESTINATION="OS=13.1,name=iPhone 11" SCHEME="$PACKAGE_SCHEME" RUN_TESTS="YES"
    - DESTINATION="OS=12.4,name=iPhone XS" SCHEME="$PACKAGE_SCHEME" RUN_TESTS="YES"
    - DESTINATION="OS=13.0,name=Apple TV 4K" SCHEME="$PACKAGE_SCHEME" RUN_TESTS="YES"
    - DESTINATION="OS=6.0,name=Apple Watch Series 5 - 44mm" SCHEME="$PACKAGE_SCHEME" RUN_TESTS="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks